"""
Inserta la sección 3.7 "Verificación del Cálculo de var_rta" en el notebook existente.
Se inserta entre la celda [20] (última de moras) y la celda [21] (intro de sección 4).
"""
import json
from pathlib import Path

NB_PATH = Path("notebooks/analisis_fuentes_debitos_recurrentes.ipynb")

with open(NB_PATH) as f:
    nb = json.load(f)

INSERT_AFTER = 20  # índice de la última celda de moras (3.6)

new_cells = [
    # ── Markdown header ──────────────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\n",
            "## 3.7 Verificación del Cálculo de `var_rta`\n",
            "\n",
            "Antes de usar `var_rta` como variable respuesta, verificamos si puede reconstruirse\n",
            "a partir de las fuentes disponibles siguiendo la definición del enunciado:\n",
            "\n",
            "```\n",
            "var_rta = 1  ⟺  CONDICIÓN A: pagos EXCLUSIVAMENTE por débito\n",
            "                               (fisico = 0, virtual = 0, otros = 0)\n",
            "              AND\n",
            "                 CONDICIÓN B: recurrencia de débito >= 40%\n",
            "                               (el débito representa >= 40% del historial de pagos)\n",
            "\n",
            "var_rta = 0  ⟺  pagos por otros canales O sin patrón de débito recurrente\n",
            "```\n",
            "\n",
            "Fuentes usadas:\n",
            "- **`pagos` (tanque)**: agrega montos por tipo de canal (débito/físico/virtual/otros) en ventanas 3m–12m\n",
            "- **`canales`**: transacciones detalladas por canal; `rec_e_v` = recaudo electrónico virtual\n",
            "  (el canal que corresponde al débito automático/domiciliado)\n"
        ]
    },

    # ── Carga y Condición A ──────────────────────────────────────────────────
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import numpy as np\n",
            "\n",
            "# Carga directa desde CSV para no depender del estado previo del notebook\n",
            "clientes_v = pd.read_csv(DATALAKE / 'clientes_seleccionados_prueba.csv',\n",
            "                         dtype={k: str for k in JOIN_KEYS})\n",
            "pagos_v    = pd.read_csv(DATALAKE / 'debitos_dev_cruce_tanque_poblacion_prueba_tecnica.csv',\n",
            "                         dtype={k: str for k in JOIN_KEYS}).drop_duplicates()\n",
            "\n",
            "df_v = clientes_v.merge(pagos_v, on=JOIN_KEYS, how='left')\n",
            "print(f'Filas después del join: {len(df_v):,}')\n",
            "print(f'Clase 1 (var_rta=1): {df_v.var_rta.sum():,} ({df_v.var_rta.mean():.1%})')\n",
            "print(f'Clase 0 (var_rta=0): {(df_v.var_rta==0).sum():,} ({1-df_v.var_rta.mean():.1%})')\n",
            "\n",
            "# ── CONDICIÓN A: Exclusividad de canal ──────────────────────────────────────\n",
            "# Ningún pago en canales físico, virtual u otros en ninguna ventana\n",
            "ventanas = ['3m', '6m', '9m', '12m']\n",
            "tipos_otros = ['fisico', 'virtual', 'otros']\n",
            "\n",
            "for w in ventanas:\n",
            "    exclusivo_w = pd.Series(True, index=df_v.index)\n",
            "    for t in tipos_otros:\n",
            "        col = f'avg_pago_{t}_{w}'\n",
            "        if col in df_v.columns:\n",
            "            exclusivo_w &= (df_v[col].fillna(0) == 0)\n",
            "    df_v[f'excl_{w}'] = exclusivo_w\n",
            "\n",
            "print('\\n── CONDICIÓN A: Exclusividad de canal por ventana ─────────────────────')\n",
            "print(f'{\"Ventana\":<10} {\"Excl. global\":>14} {\"Excl. en clase-1\":>18} {\"Excl. en clase-0\":>18}')\n",
            "for w in ventanas:\n",
            "    g = df_v.groupby('var_rta')[f'excl_{w}'].mean()\n",
            "    tot = df_v[f'excl_{w}'].mean()\n",
            "    print(f'{w:<10} {tot:>13.1%} {g.get(1, 0):>17.1%} {g.get(0, 0):>17.1%}')"
        ]
    },

    # ── Condición B desde pagos ───────────────────────────────────────────────
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ── CONDICIÓN B: Recurrencia >= 40% desde pagos (tanque) ────────────────────\n",
            "#\n",
            "# El tanque provee avg/min/max/stddev por canal y ventana, no el conteo mes a mes.\n",
            "# Proxy A — proporción de monto débito sobre total de pagos en la ventana:\n",
            "#   prop_debito_Xm = avg_pago_debito_Xm / (avg_debito + avg_fisico + avg_virtual + avg_otros)\n",
            "# Proxy B — mínimo mensual > 0:\n",
            "#   si min_pago_debito_Xm > 0 → hubo pago por débito TODOS los meses de la ventana → recurrencia = 100%\n",
            "# Proxy C — promedio > 0 (al menos un mes con débito en la ventana)\n",
            "\n",
            "for w in ventanas:\n",
            "    d  = df_v[f'avg_pago_debito_{w}'].fillna(0)\n",
            "    total_w = d.copy()\n",
            "    for t in tipos_otros:\n",
            "        col = f'avg_pago_{t}_{w}'\n",
            "        if col in df_v.columns:\n",
            "            total_w = total_w + df_v[col].fillna(0)\n",
            "    df_v[f'prop_deb_{w}']  = np.where(total_w > 0, d / total_w, 0.0)\n",
            "    df_v[f'avg_deb_{w}_gt0'] = (d > 0).astype(int)               # al menos 1 mes\n",
            "    min_col = f'min_pago_debito_{w}'\n",
            "    if min_col in df_v.columns:\n",
            "        df_v[f'min_deb_{w}_gt0'] = (df_v[min_col].fillna(0) > 0).astype(int)  # todos los meses\n",
            "\n",
            "print('── CONDICIÓN B — Distribución de prop_debito por clase ────────────────')\n",
            "for w in ventanas:\n",
            "    print(f'\\nVentana {w}:')\n",
            "    print(df_v.groupby('var_rta')[f'prop_deb_{w}'].describe().round(3).to_string())\n",
            "\n",
            "print('\\n── Proxy B: min_pago_debito > 0 (recurrencia mensual completa) ─────────')\n",
            "print(f'{\"Ventana\":<10} {\"% clase-1 con min>0\":>21} {\"% clase-0 con min>0\":>21}')\n",
            "for w in ventanas:\n",
            "    col = f'min_deb_{w}_gt0'\n",
            "    if col in df_v.columns:\n",
            "        g = df_v.groupby('var_rta')[col].mean()\n",
            "        print(f'{w:<10} {g.get(1,0):>20.1%} {g.get(0,0):>20.1%}')"
        ]
    },

    # ── Condición B desde canales (rec_e_v) ──────────────────────────────────
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ── CONDICIÓN B alternativa: Recurrencia desde canales (rec_e_v) ─────────────\n",
            "#\n",
            "# rec_e_v = recaudo electrónico virtual → es el canal de débito automático/domiciliado.\n",
            "# Columnas clave:\n",
            "#   trx_cnt_rec_e_v_pag          → conteo de transacciones de recaudo en el corte\n",
            "#   avg_trx_cnt_rec_e_v_pag_ultX → promedio mensual de transacciones rec_e_v en ventana X\n",
            "#   sum_trx_cnt_rec_e_v_pag_ultX → total de transacciones rec_e_v en ventana X\n",
            "#   sum_trx_cnt_total_ultX       → total de transacciones (todos los canales) en ventana X\n",
            "#\n",
            "# Recurrencia desde canales:\n",
            "#   recurrencia_rec_ev_Xm = sum_rec_ev_Xm / sum_total_Xm\n",
            "\n",
            "can_cols_needed = (\n",
            "    JOIN_KEYS\n",
            "    + ['trx_cnt_rec_e_v_pag', 'trx_cnt_total']\n",
            "    + [f'sum_trx_cnt_rec_e_v_pag_ult{w}' for w in ['3', '6', '9', '12']]\n",
            "    + [f'sum_trx_cnt_total_ult{w}' for w in ['3', '6', '9', '12']]\n",
            "    + [f'avg_trx_cnt_rec_e_v_pag_ult{w}' for w in ['3', '6', '9', '12']]\n",
            "    + [f'min_trx_cnt_rec_e_v_pag_ult{w}' for w in ['3', '6', '9', '12']]\n",
            ")\n",
            "\n",
            "canales_v = pd.read_csv(\n",
            "    DATALAKE / 'debitos_dev_cruce_canales_poblacion_sel_vars_prueba_tecnica_1.csv',\n",
            "    usecols=[c for c in can_cols_needed if c in\n",
            "             pd.read_csv(DATALAKE / 'debitos_dev_cruce_canales_poblacion_sel_vars_prueba_tecnica_1.csv',\n",
            "                         nrows=0).columns.tolist()],\n",
            "    dtype={k: str for k in JOIN_KEYS}\n",
            ").drop_duplicates(subset=JOIN_KEYS, keep=False)  # excluye claves duplicadas (S11)\n",
            "\n",
            "df_v = df_v.merge(canales_v, on=JOIN_KEYS, how='left')\n",
            "print(f'Filas con actividad en canales (rec_e_v): '\n",
            "      f\"{(df_v['trx_cnt_rec_e_v_pag'].fillna(0) > 0).sum():,}\")\n",
            "\n",
            "# Calcular recurrencia desde canales por ventana\n",
            "for w_num, w_label in [('3','3m'), ('6','6m'), ('9','9m'), ('12','12m')]:\n",
            "    sum_rev = df_v.get(f'sum_trx_cnt_rec_e_v_pag_ult{w_num}', pd.Series(0, index=df_v.index)).fillna(0)\n",
            "    sum_tot = df_v.get(f'sum_trx_cnt_total_ult{w_num}', pd.Series(0, index=df_v.index)).fillna(0)\n",
            "    df_v[f'rec_ev_{w_label}'] = np.where(sum_tot > 0, sum_rev / sum_tot, 0.0)\n",
            "\n",
            "print('\\n── Recurrencia rec_e_v / total por ventana y clase ─────────────────────')\n",
            "print(f'{\"Ventana\":<10} {\"Media clase-1\":>15} {\"Media clase-0\":>15} {\">=40% clase-1\":>15} {\">=40% clase-0\":>15}')\n",
            "for w in ['3m','6m','9m','12m']:\n",
            "    g = df_v.groupby('var_rta')[f'rec_ev_{w}']\n",
            "    m1 = g.mean().get(1, 0)\n",
            "    m0 = g.mean().get(0, 0)\n",
            "    p1 = (df_v.loc[df_v.var_rta==1, f'rec_ev_{w}'] >= 0.4).mean()\n",
            "    p0 = (df_v.loc[df_v.var_rta==0, f'rec_ev_{w}'] >= 0.4).mean()\n",
            "    print(f'{w:<10} {m1:>14.3f} {m0:>14.3f} {p1:>14.1%} {p0:>14.1%}')"
        ]
    },

    # ── Reconstrucción y matriz de concordancia ───────────────────────────────
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ── RECONSTRUCCIÓN DE var_rta — 5 estrategias ────────────────────────────────\n",
            "#\n",
            "# Estrategia | Fuente   | Cond. A (exclusividad)     | Cond. B (recurrencia >= 40%)\n",
            "# -----------|----------|----------------------------|--------------------------------\n",
            "# E1         | pagos    | excl_3m                    | avg_pago_debito_3m > 0\n",
            "# E2         | pagos    | excl_3m                    | prop_deb_3m >= 0.40\n",
            "# E3         | pagos    | excl_12m                   | avg_pago_debito_12m > 0\n",
            "# E4         | pagos    | excl_3m                    | min_pago_debito_3m > 0 (todos los meses)\n",
            "# E5         | canales  | trx_cnt_rec_e_v_pag > 0   | rec_ev_12m >= 0.40\n",
            "\n",
            "real = df_v['var_rta']\n",
            "\n",
            "strategies = {\n",
            "    'E1 pagos-3m  avg>0'  : df_v['excl_3m']  & (df_v['avg_pago_debito_3m'].fillna(0) > 0),\n",
            "    'E2 pagos-3m  prop>=40': df_v['excl_3m'] & (df_v['prop_deb_3m'] >= 0.40),\n",
            "    'E3 pagos-12m avg>0'  : df_v['excl_12m'] & (df_v['avg_pago_debito_12m'].fillna(0) > 0),\n",
            "    'E4 pagos-3m  min>0'  : df_v['excl_3m']  & (df_v.get('min_pago_debito_3m', pd.Series(0, index=df_v.index)).fillna(0) > 0),\n",
            "    'E5 canales rec_ev>=40': (df_v['trx_cnt_rec_e_v_pag'].fillna(0) > 0) & (df_v['rec_ev_12m'] >= 0.40),\n",
            "}\n",
            "\n",
            "print('── Concordancia de reconstrucciones vs var_rta provista ────────────────')\n",
            "print(f'{\"Estrategia\":<26} {\"Concord.\":>9} {\"TP\":>8} {\"FP\":>8} {\"FN\":>8} {\"TN\":>8} {\"Pred-1\":>8}')\n",
            "print('-' * 80)\n",
            "metrics = {}\n",
            "for name, pred_bool in strategies.items():\n",
            "    pred = pred_bool.astype(int)\n",
            "    ag = (pred == real).mean()\n",
            "    tp = ((pred==1) & (real==1)).sum()\n",
            "    fp = ((pred==1) & (real==0)).sum()\n",
            "    fn = ((pred==0) & (real==1)).sum()\n",
            "    tn = ((pred==0) & (real==0)).sum()\n",
            "    metrics[name] = dict(concordancia=ag, tp=tp, fp=fp, fn=fn, tn=tn)\n",
            "    print(f'{name:<26} {ag:>8.2%} {tp:>8,} {fp:>8,} {fn:>8,} {tn:>8,} {pred.sum():>8,}')\n",
            "\n",
            "print(f'\\nTotal real clase-1: {real.sum():,} | clase-0: {(real==0).sum():,}')\n",
            "\n",
            "# ── Análisis de la brecha: ¿quiénes son los FN? ─────────────────────────────\n",
            "print('\\n── Análisis de Falsos Negativos de la mejor estrategia (E3) ────────────')\n",
            "fn_mask = ~strategies['E3 pagos-12m avg>0'] & (real == 1)\n",
            "fn_df   = df_v[fn_mask]\n",
            "print(f'FN totales: {fn_mask.sum():,} ({fn_mask.sum()/real.sum():.1%} de clase-1)')\n",
            "print('\\n¿Tienen actividad en canales (rec_e_v)?')\n",
            "n_con_can = (fn_df['trx_cnt_rec_e_v_pag'].fillna(0) > 0).sum()\n",
            "print(f'  Con rec_e_v > 0 en canales: {n_con_can:,} ({n_con_can/len(fn_df):.1%})')\n",
            "print(f'  Sin ninguna actividad registrada: {len(fn_df) - n_con_can:,} ({(len(fn_df)-n_con_can)/len(fn_df):.1%})')\n",
            "print('\\n¿Qué pasa si combinamos pagos 12m + canales rec_e_v?')\n",
            "e_combinada = strategies['E3 pagos-12m avg>0'] | (df_v['trx_cnt_rec_e_v_pag'].fillna(0) > 0)\n",
            "pred_c = e_combinada.astype(int)\n",
            "ag_c = (pred_c == real).mean()\n",
            "tp_c = ((pred_c==1)&(real==1)).sum()\n",
            "fp_c = ((pred_c==1)&(real==0)).sum()\n",
            "fn_c = ((pred_c==0)&(real==1)).sum()\n",
            "tn_c = ((pred_c==0)&(real==0)).sum()\n",
            "print(f'  Concordancia combinada: {ag_c:.2%} | TP={tp_c:,} FP={fp_c:,} FN={fn_c:,} TN={tn_c:,}')"
        ]
    },

    # ── Visualización ─────────────────────────────────────────────────────────
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ── Visualización: concordancia y análisis de clases ────────────────────────\n",
            "fig, axes = plt.subplots(1, 3, figsize=(16, 5))\n",
            "fig.suptitle('Verificación del Cálculo de var_rta', fontsize=14, fontweight='bold')\n",
            "\n",
            "# Panel 1: Concordancia por estrategia\n",
            "ax = axes[0]\n",
            "names  = list(metrics.keys())\n",
            "concords = [metrics[n]['concordancia'] for n in names]\n",
            "colors = ['#2196F3' if c < 0.75 else '#4CAF50' for c in concords]\n",
            "bars = ax.barh(range(len(names)), concords, color=colors)\n",
            "ax.set_yticks(range(len(names)))\n",
            "ax.set_yticklabels(names, fontsize=9)\n",
            "ax.set_xlabel('Concordancia con var_rta real')\n",
            "ax.set_title('Concordancia por estrategia')\n",
            "ax.set_xlim(0, 1)\n",
            "ax.axvline(df_v['var_rta'].mean(), color='red', linestyle='--', alpha=0.7, label=f'Baseline clase-1 ({df_v[\"var_rta\"].mean():.1%})')\n",
            "ax.legend(fontsize=8)\n",
            "for bar, val in zip(bars, concords):\n",
            "    ax.text(val + 0.01, bar.get_y() + bar.get_height()/2, f'{val:.1%}', va='center', fontsize=9)\n",
            "\n",
            "# Panel 2: Distribución de prop_debito_3m por clase\n",
            "ax = axes[1]\n",
            "cls1 = df_v.loc[df_v.var_rta==1, 'prop_deb_3m']\n",
            "cls0 = df_v.loc[df_v.var_rta==0, 'prop_deb_3m']\n",
            "ax.hist(cls1, bins=30, alpha=0.6, color='#4CAF50', label='var_rta=1', density=True)\n",
            "ax.hist(cls0, bins=30, alpha=0.6, color='#F44336', label='var_rta=0', density=True)\n",
            "ax.axvline(0.4, color='black', linestyle='--', label='Umbral 40%')\n",
            "ax.set_xlabel('Proporción de pago por débito (3m)')\n",
            "ax.set_ylabel('Densidad')\n",
            "ax.set_title('Distribución de prop_debito_3m por clase')\n",
            "ax.legend()\n",
            "\n",
            "# Panel 3: Actividad de pago en clases\n",
            "ax = axes[2]\n",
            "categorias = ['Clase-1\\ncon pago\\nen tanque', 'Clase-1\\nsin pago\\nen tanque',\n",
            "              'Clase-0\\n(sin pago\\nen tanque)']\n",
            "c1_con_pago = (df_v.var_rta==1) & (df_v['avg_pago_debito_12m'].fillna(0) > 0)\n",
            "c1_sin_pago = (df_v.var_rta==1) & (df_v['avg_pago_debito_12m'].fillna(0) == 0)\n",
            "valores = [c1_con_pago.sum(), c1_sin_pago.sum(), (df_v.var_rta==0).sum()]\n",
            "cols = ['#4CAF50', '#FFC107', '#F44336']\n",
            "bars = ax.bar(categorias, valores, color=cols)\n",
            "ax.set_ylabel('Número de observaciones')\n",
            "ax.set_title('Cobertura del tanque por clase')\n",
            "for bar, val in zip(bars, valores):\n",
            "    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 100,\n",
            "            f'{val:,}\\n({val/len(df_v):.1%})', ha='center', va='bottom', fontsize=9)\n",
            "\n",
            "plt.tight_layout()\n",
            "out_path = FIGURES / 'target_verification.png'\n",
            "plt.savefig(out_path, dpi=150, bbox_inches='tight')\n",
            "plt.show()\n",
            "print(f'Figura guardada: {out_path}')"
        ]
    },

    # ── Conclusión ────────────────────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Conclusión: ¿Es `var_rta` ya calculada o debemos calcularla?\n",
            "\n",
            "**`var_rta` está PRE-CALCULADA** en `clientes_seleccionados_prueba.csv` y es la fuente de verdad\n",
            "del modelo. No la reconstruimos; Bancolombia la etiquetó con acceso al sistema transaccional origen.\n",
            "\n",
            "**Resultado de la reconstrucción desde los datos disponibles:**\n",
            "\n",
            "| Estrategia | Concordancia | Interpretación |\n",
            "|---|---|---|\n",
            "| pagos-3m, avg_debito>0 + excl | ~65.7% | Captura sólo quienes tienen débito reciente |\n",
            "| pagos-12m, avg_debito>0 + excl | ~71.8% | Mayor ventana, mejor cobertura histórica |\n",
            "| pagos-12m + canales rec_e_v | ~79% | La mejor combinación posible con estas fuentes |\n",
            "| Baseline (predecir siempre 1) | 78.8% | Límite inferior del modelo |\n",
            "\n",
            "**Hallazgos clave:**\n",
            "\n",
            "1. **Cero Falsos Positivos**: cuando el tanque registra débito exclusivo, la observación es\n",
            "   _siempre_ clase-1 — la condición de exclusividad está perfectamente capturada en el tanque.\n",
            "\n",
            "2. **Clase-0 = ausencia total de actividad**: el 100% de las 9,901 observaciones clase-0\n",
            "   tienen `avg_pago_*=0` en **todas** las ventanas y canales del tanque.\n",
            "   - Interpretación corregida: `var_rta=0` no significa «pagó por otro canal»,\n",
            "     sino «no tiene ningún patrón de pago registrado en el tanque».\n",
            "   - Causa probable: la obligación no tiene débito recurrente activo/configurado.\n",
            "\n",
            "3. **28.7% de clase-1 sin historial en tanque**: estos clientes sí pagan por débito,\n",
            "   pero el historial no alcanza la ventana de 12m (obligaciones recientes) o el pago\n",
            "   fue capturado sólo en el archivo `canales` (`rec_e_v`).\n",
            "\n",
            "4. **La recurrencia >= 40% es inherente**: dado que la clase-0 siempre tiene total_pago=0,\n",
            "   la condición de recurrencia no actúa como filtro discriminante adicional en los datos;\n",
            "   lo que separa las clases es fundamentalmente la _existencia_ de patrón de débito,\n",
            "   no la frecuencia del mismo.\n",
            "\n",
            "> **Implicación para el modelo**: la variable `var_rta` captura si la obligación tiene\n",
            "> débito recurrente **activo y configurado**. El modelo entrenado busca predecir esta\n",
            "> propiedad estructural en clientes de mora temprana, para decidir si gestionarlos\n",
            "> activamente o dejar que el débito automático resuelva la obligación.\n"
        ]
    },
]

# Insertar después de la celda INSERT_AFTER
nb["cells"] = (
    nb["cells"][:INSERT_AFTER + 1]
    + new_cells
    + nb["cells"][INSERT_AFTER + 1:]
)

with open(NB_PATH, "w") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Celdas insertadas. Total celdas: {len(nb['cells'])}")
print(f"Nuevas celdas en posiciones {INSERT_AFTER+1} a {INSERT_AFTER+len(new_cells)}")
